// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import swag "github.com/venosm/swaggo"

const docTemplateCustomDelims = `{
    "components": {
        "schemas": {
            "api.MyStruct": {
                "properties": {
                    "urltemplate": {
                        "example": "http://example.org/{{ path }}",
                        "type": "string"
                    }
                },
                "type": "object"
            }
        }
    },
    "info": {
        "contact": {},
        "description": "{%escape .Description%}",
        "termsOfService": "http://swagger.io/terms/",
        "title": "{%.Title%}",
        "version": "{%.Version%}"
    },
    "openapi": "3.0.0",
    "paths": {
        "/myfunc": {
            "get": {
                "description": "My Function",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/components/schemas/api.MyStruct"
                        }
                    }
                }
            }
        }
    },
    "servers": [
        {
            "url": "http://{%.Host%}{%.BasePath%}"
        }
    ]
}`

// SwaggerInfoCustomDelims holds exported Swagger Info so clients can modify it
var SwaggerInfoCustomDelims = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "Testing custom template delimeters",
	InfoInstanceName: "CustomDelims",
	SwaggerTemplate:  docTemplateCustomDelims,
	LeftDelim:        "{%",
	RightDelim:       "%}",
}

func init() {
	swag.Register(SwaggerInfoCustomDelims.InstanceName(), SwaggerInfoCustomDelims)
}
