// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/venosm/swaggo"

const docTemplate = `{
    "components": {
        "schemas": {
            "main.StavZpravy": {
                "enum": [
                    "AKTIVNI",
                    "ARCHIVOVANA",
                    "SMAZANA"
                ],
                "type": "string",
                "x-enum-varnames": [
                    "StavAktivni",
                    "StavArchivovana",
                    "StavSmazana"
                ]
            },
            "main.Zprava": {
                "properties": {
                    "id": {
                        "example": 1,
                        "type": "integer"
                    },
                    "stav_zpravy": {
                        "allOf": [
                            {
                                "$ref": "#/components/schemas/main.StavZpravy"
                            }
                        ],
                        "description": "Stav zprávy (defaultní hodnota je aktivní).",
                        "enum": [
                            "AKTIVNI",
                            "ARCHIVOVANA",
                            "SMAZANA"
                        ],
                        "example": "AKTIVNI"
                    }
                },
                "type": "object"
            }
        }
    },
    "info": {
        "contact": {},
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "openapi": "3.0.0",
    "paths": {
        "/test": {
            "get": {
                "description": "Test endpoint for enum duplication",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/main.Zprava"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Test endpoint",
                "tags": [
                    "test"
                ]
            }
        }
    },
    "servers": [
        {
            "url": "http://{{.Host}}{{.BasePath}}"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Test API pro enum duplicity",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
