// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import swag "github.com/venosm/swaggo"

const docTemplate = `{
    "components": {
        "schemas": {
            "main.ChybovaOdpoved": {
                "properties": {
                    "kod": {
                        "description": "HTTP status kód chyby",
                        "example": 400,
                        "type": "integer"
                    },
                    "zprava": {
                        "description": "Popis chyby pro uživatele",
                        "example": "Špatný požadavek",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "main.UspesnaOdpoved": {
                "properties": {
                    "data": {
                        "description": "Volitelná data odpovědi"
                    },
                    "zprava": {
                        "description": "Zpráva o úspěchu operace",
                        "example": "Operace proběhla úspěšně",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "main.Uzivatel": {
                "properties": {
                    "datum_registrace": {
                        "description": "Datum a čas registrace",
                        "example": "2023-01-01T00:00:00Z",
                        "type": "string"
                    },
                    "email": {
                        "description": "Emailová adresa uživatele",
                        "example": "jan.novak@example.com",
                        "type": "string"
                    },
                    "id": {
                        "description": "Jedinečný identifikátor uživatele",
                        "example": 1,
                        "type": "integer"
                    },
                    "je_aktivni": {
                        "description": "Indikátor aktivity uživatele",
                        "example": true,
                        "type": "boolean"
                    },
                    "jmeno": {
                        "description": "Celé jméno uživatele",
                        "example": "Jan Novák",
                        "type": "string"
                    },
                    "vek": {
                        "description": "Věk uživatele v letech",
                        "example": 25,
                        "maximum": 150,
                        "minimum": 0,
                        "type": "integer"
                    }
                },
                "type": "object"
            },
            "main.UzivatelRequest": {
                "properties": {
                    "email": {
                        "description": "Email nového uživatele",
                        "example": "jan.novak@example.com",
                        "type": "string"
                    },
                    "jmeno": {
                        "description": "Jméno nového uživatele",
                        "example": "Jan Novák",
                        "type": "string"
                    },
                    "vek": {
                        "description": "Věk nového uživatele",
                        "example": 25,
                        "maximum": 150,
                        "minimum": 0,
                        "type": "integer"
                    }
                },
                "required": [
                    "email",
                    "jmeno",
                    "vek"
                ],
                "type": "object"
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI Specifikace",
        "url": "https://swagger.io/resources/open-api/"
    },
    "info": {
        "contact": {
            "email": "support@swagger.io",
            "name": "API Support",
            "url": "http://www.swagger.io/support"
        },
        "description": "{{escape .Description}}",
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "termsOfService": "http://swagger.io/terms/",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "openapi": "3.0.0",
    "paths": {
        "/uzivatele": {
            "get": {
                "description": "Tento endpoint slouží k získání informací o konkrétním uživateli na základě jeho jedinečného ID.\n\n### Použití\n\nOdešlete GET požadavek na ` + "`" + `/uzivatele/{id}` + "`" + ` kde ` + "`" + `{id}` + "`" + ` je číselný identifikátor uživatele.\n\n### Návratové hodnoty\n\n- **200 OK**: Uživatel byl nalezen a jeho data jsou vrácena\n- **404 Not Found**: Uživatel s daným ID neexistuje\n- **500 Internal Server Error**: Chyba serveru\n\n### Bezpečnost\n\nTento endpoint vyžaduje platný autentifikační token v Authorization hlavičce.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/main.Uzivatel"
                                }
                            }
                        },
                        "description": "Konkrétní uživatel"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/main.ChybovaOdpoved"
                                }
                            }
                        },
                        "description": "Uživatel nenalezen"
                    }
                },
                "summary": "Získej uživatele",
                "tags": [
                    "uzivatele"
                ]
            },
            "post": {
                "description": "Vytvoří nového uživatele v systému",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/main.UzivatelRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "allOf": [
                                        {
                                            "$ref": "#/components/schemas/main.UspesnaOdpoved"
                                        },
                                        {
                                            "properties": {
                                                "data": {
                                                    "$ref": "#/components/schemas/main.Uzivatel"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    ]
                                }
                            }
                        },
                        "description": "Uživatel byl úspěšně vytvořen"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/main.ChybovaOdpoved"
                                }
                            }
                        },
                        "description": "Špatný požadavek"
                    }
                },
                "summary": "Vytvoř nového uživatele",
                "tags": [
                    "uzivatele"
                ]
            }
        },
        "/uzivatele/{id}": {
            "get": {
                "description": "Tento endpoint slouží k získání informací o konkrétním uživateli na základě jeho jedinečného ID.\n\n### Použití\n\nOdešlete GET požadavek na ` + "`" + `/uzivatele/{id}` + "`" + ` kde ` + "`" + `{id}` + "`" + ` je číselný identifikátor uživatele.\n\n### Návratové hodnoty\n\n- **200 OK**: Uživatel byl nalezen a jeho data jsou vrácena\n- **404 Not Found**: Uživatel s daným ID neexistuje\n- **500 Internal Server Error**: Chyba serveru\n\n### Bezpečnost\n\nTento endpoint vyžaduje platný autentifikační token v Authorization hlavičce.",
                "parameters": [
                    {
                        "description": "ID uživatele",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/main.Uzivatel"
                                }
                            }
                        },
                        "description": "Konkrétní uživatel"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/main.ChybovaOdpoved"
                                }
                            }
                        },
                        "description": "Uživatel nenalezen"
                    }
                },
                "summary": "Získej uživatele",
                "tags": [
                    "uzivatele"
                ]
            }
        }
    },
    "servers": [
        {
            "url": "http://{{.Host}}{{.BasePath}}"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API pro správu uživatelů",
	Description:      "<details>\n  <summary><b><font size=\"5\">Základní aplikační logika</font></b></summary>\n  <p>Toto REST API k elektronické komunikaci pro dodavatele s architekturou REST a formátem dat JSON s kódováním UTF8. Autentizace probíhá na základě certifikátu.</p>\n</details>\n\n<details>\n  <summary><b><font size=\"5\">Operace webové služby</font></b></summary>\n\n### Zaevidování zprávy zadavateli\nPro zaevidování zprávy se používá endpoint **POST /servisni/zprava-zadavali**. Očekává požadavek typu `multipart/form-data` se dvěma částmi: `zpravaJson` (JSON s daty zprávy) a volitelnými `prilohy` (soubory s maximální celkovou velikostí 1 GB).\n\n### Zaevidování přečtení zprávy zadavali\nEndpoint **POST /servisni/zprava-zadavali/precteni** slouží k zaevidování přečtení zprávy. Přečtení lze zaevidovat pouze u zprávy, která byla zaevidována stejným elektronickým nástrojem.\n\n### Detail zprávy zadavateli\nPro načtení detailu zprávy je k dispozici endpoint **GET /servisni/zprava-zadavali/{id}**, kde `{id}` je UUID zprávy.\n\n### Smazání zprávy zadavateli\nEndpoint **DELETE /servisni/zprava-zadavali/{id}** umožňuje smazání zprávy. Smazat lze pouze zprávy, které pocházejí ze stejného elektronického nástroje, který je evidoval.\n</details>\n\n---\n\n<b><font size=\"5\">Seznam změn</font></b>\n### Aktuální verze\n\n<details>\n  <summary>1.0.0</summary>\n\n#### Inicializační verze\n- Implementace základních operací pro správu zpráv.\n- Podpora zaevidování zprávy s přílohami.\n- Možnost zaznamenat přečtení zprávy a získat její detail.\n- Funkce pro smazání zprávy s omezením na nástroj, který ji vytvořil.\n</details>",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
